FROM oven/bun:1

ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL

WORKDIR /usr/src/app

COPY package.json bun.lock ./
COPY apps/web/package.json apps/web/package.json

# Copy workspace package.json files as needed
COPY packages ./packages

COPY turbo.json ./   

COPY apps/web ./apps/web

RUN bun install --frozen-lockfile

WORKDIR /usr/src/app/

RUN bun run generate:db

RUN bun run turbo run build --filter=web...

EXPOSE 3000

CMD ["bun", "run", "start:web"]