FROM oven/bun:1

ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL

WORKDIR /usr/src/app/apps/web

COPY package.json bun.lock ./


COPY . .

RUN bun install 
RUN bun run generate:db

RUN bunx turbo build --filter=web...

EXPOSE 3000

CMD ["bun", "run", "start"]