name: Continuous Deployment (Prod) (next-app)
on:
  push:
    branches: [ main ]
jobs:
  build:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Verify user  secret
        run: echo "${{ secrets.DOCKERHUB_USERNAME }}"
      - name: Verify token secret
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}"  

      - name: Build and push
        uses: docker/build-push-action@v4
        
        with:
          context: .
          file: ./Dockerfile.next
          push: true
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
         
          tags: optimusprime0801/ci-cd-next:${{ github.sha }}
      
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 52.90.222.209
          username: ubuntu
          key: ${{ secrets.SSH_KEY_PK }}
          port: 22

          script: |
            echo "Pulling new Docker image..."

            docker pull optimusprime0801/ci-cd-next:${{ github.sha }}

            echo "Stopping old container..."

            docker stop backend || true
            docker rm backend || true

            echo "Starting new container..."

            docker run -d \
              --name backend \
              --restart unless-stopped \
              -p 3000:3000 \
              optimusprime0801/ci-cd-next:${{ github.sha }}

            echo "Deployment complete!"

            docker ps  